services:
  postgres:
    image: 'postgres:17-alpine'
    container_name: '${CONTAINER_NAME:-postgres-container}'
    environment:
      - 'POSTGRES_DB=${DB_NAME:-proyecto_juegos}'
      - 'POSTGRES_PASSWORD=${DB_PASSWORD:-Empanada5678}'
      - 'POSTGRES_USER=${DB_USER:-nico}'
    ports:
      - '5432:5432'
    volumes:
      - 'postgres-data:/var/lib/postgresql/data'

  app:
    build: .
    container_name: 'juegos-app'
    ports:
      - '9090:8080'
    depends_on:
      - postgres
    environment:
      - 'PORT=8080'
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/proyecto_juegos'
      - 'SPRING_DATASOURCE_USERNAME=nico'
      - 'SPRING_PROFILES_ACTIVE=dev'
      - 'KEY_JWT_SECRET=Uo4MkxmgYVdBK+6mYtjYYpI8k4fpSUihZ8FNhpiSmZ4xyb59cUYKLdW94eKtkoRe'
      - 'CLOUDINARY_URL=cloudinary://312127544695893:sbCqVOP04vt4hJrmryY0ojeEOPs@tpjbimjw'
      - 'R2_ACCOUNT_ID=cf9e0f7fa105c15259b487b0a447d09b'
      - 'R2_ACCESS_KEY_ID=dbe4102d8a1e851b23b409a9510b63a2'
      - 'R2_SECRET_ACCESS_KEY=abcdf7e7b485a9aad72e1c310e8a1181ad79649bf1c8bcc4bac085cdb55d9ff6'
      - 'R2_BUCKET=trailers'
      - 'R2_PUBLIC_BASE_URL=https://pub-58f3bb038ab8451e96fb292f7cb1dc15.r2.dev'

volumes:
  postgres-data:
