spring:
  jpa:
    show-sql: false

logging:
  level:
    com.app.proyectojuegosmonolito: WARN

springdoc:
    api-docs:
      enabled: false
    swagger-ui:
      enabled: false
server:
  shutdown: graceful