spring:
  jpa:
    show-sql: true

app:
  jwt:
    secret: ${KEY_JWT_SECRET:O7E6XGIhr7)k<W>U,,uWrFe;U[)qPeV+&}
    expiration: ${KEY_JWT_EXPIRATION:3600000}

logging:
  level:
    com.app.proyectojuegosmonolito: DEBUG
    org.hibernate.SQL: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,mappings,loggers