spring:
  application:
    name: proyecto_juegos_monolito
  config:
    import: "optional:file:.env[.properties]"
  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME:proyecto_juegos}
    username: ${DB_USER:nico}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true

app:
  seed:
    enabled: true
  jwt:
    secret: ${KEY_JWT_SECRET}
    expiration: ${KEY_JWT_EXPIRATION:3600000}
  cloudinary:
    url: ${CLOUDINARY_URL}

logging:
  level:
    com.app.proyectojuegosmonolito: DEBUG
    org.hibernate.SQL: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,mappings,loggers
