package com.app.proyectojuegosmonolito.account.profile.model;

import lombok.Getter;

@Getter
public enum Comuna {
    // XV Región de Arica y Parinacota
    ARICA("Arica"),
    CAMARONES("Camarones"),
    PUTRE("Putre"),
    GENERAL_LAGOS("General Lagos"),

    // I Región de Tarapacá
    IQUIQUE("Iquique"),
    ALTO_HOSPICIO("Alto Hospicio"),
    POZO_ALMONTE("Pozo Almonte"),
    CAMINA("Camiña"),
    COLCHANE("Colchane"),
    HUARA("Huara"),
    PICA("Pica"),

    // II Región de Antofagasta
    ANTOFAGASTA("Antofagasta"),
    MEJILLONES("Mejillones"),
    SIERRA_GORDA("Sierra Gorda"),
    TALTAL("Taltal"),
    CALAMA("Calama"),
    OLLAGUE("Ollagüe"),
    SAN_PEDRO_DE_ATACAMA("San Pedro de Atacama"),
    TOCOPILLA("Tocopilla"),
    MARIA_ELENA("María Elena"),

    // III Región de Atacama
    COPIAPO("Copiapó"),
    CALDERA("Caldera"),
    TIERRA_AMARILLA("Tierra Amarilla"),
    CHANARAL("Chañaral"),
    DIEGO_DE_ALMAGRO("Diego de Almagro"),
    VALLENAR("Vallenar"),
    ALTO_DEL_CARMEN("Alto del Carmen"),
    FREIRINA("Freirina"),
    HUASCO("Huasco"),

    // IV Región de Coquimbo
    LA_SERENA("La Serena"),
    COQUIMBO("Coquimbo"),
    ANDACOLLO("Andacollo"),
    LA_HIGUERA("La Higuera"),
    PAIGUANO("Paiguano"),
    VICUÑA("Vicuña"),
    ILLAPEL("Illapel"),
    CANELA("Canela"),
    LOS_VILOS("Los Vilos"),
    SALAMANCA("Salamanca"),
    OVALLE("Ovalle"),
    COMBARBALA("Combarbalá"),
    MONTE_PATRIA("Monte Patria"),
    PUNITAQUI("Punitaqui"),
    RIO_HURTADO("Río Hurtado"),

    // V Región de Valparaíso
    VALPARAISO("Valparaíso"),
    CASABLANCA("Casablanca"),
    CONCON("Concón"),
    JUAN_FERNANDEZ("Juan Fernández"),
    PUCHUNCAVÍ("Puchuncaví"),
    QUINTERO("Quintero"),
    VIÑA_DEL_MAR("Viña del Mar"),
    ISLA_DE_PASCUA("Isla de Pascua"),
    LOS_ANDES("Los Andes"),
    CALLE_LARGA("Calle Larga"),
    RINCONADA("Rinconada"),
    SAN_ESTEBAN("San Esteban"),
    LA_LIGUA("La Ligua"),
    CABILDO("Cabildo"),
    PAPUDO("Papudo"),
    PETORCA("Petorca"),
    ZAPALLAR("Zapallar"),
    QUILLOTA("Quillota"),
    CALERA("Calera"),
    HIJUELAS("Hijuelas"),
    LA_CRUZ("La Cruz"),
    NOGALES("Nogales"),
    SAN_ANTONIO("San Antonio"),
    ALGARROBO("Algarrobo"),
    CARTAGENA("Cartagena"),
    EL_QUISCO("El Quisco"),
    EL_TABO("El Tabo"),
    SANTO_DOMINGO("Santo Domingo"),
    SAN_FELIPE("San Felipe"),
    CATEMU("Catemu"),
    LLAILLAY("Llaillay"),
    PANQUEHUE("Panquehue"),
    PUTAENDO("Putaendo"),
    SANTA_MARIA("Santa María"),
    QUILPUE("Quilpué"),
    LIMACHE("Limache"),
    OLMUE("Olmué"),
    VILLA_ALEMANA("Villa Alemana"),

    // VI Región de O'Higgins
    RANCAGUA("Rancagua"),
    CODEGUA("Codegua"),
    COINCO("Coinco"),
    COLTAUCO("Coltauco"),
    DONIHUE("Doñihue"),
    GRANEROS("Graneros"),
    LAS_CABRAS("Las Cabras"),
    MACHALI("Machalí"),
    MALLOA("Malloa"),
    MOSTAZAL("Mostazal"),
    OLIVAR("Olivar"),
    PEUMO("Peumo"),
    PICHIDEGUA("Pichidegua"),
    QUINTA_DE_TILCOCO("Quinta de Tilcoco"),
    RENGO("Rengo"),
    REQUINOA("Requínoa"),
    SAN_VICENTE("San Vicente"),
    PICHILEMU("Pichilemu"),
    LA_ESTRELLA("La Estrella"),
    LITUECHE("Litueche"),
    MARCHIHUE("Marchihue"),
    NAVIDAD("Navidad"),
    PAREDONES("Paredones"),
    SAN_FERNANDO("San Fernando"),
    CHEPICA("Chépica"),
    CHIMBARONGO("Chimbarongo"),
    LOLOL("Lolol"),
    NANCAGUA("Nancagua"),
    PALMILLA("Palmilla"),
    PERALILLO("Peralillo"),
    PLACILLA("Placilla"),
    PUMANQUE("Pumanque"),
    SANTA_CRUZ("Santa Cruz"),

    // VII Región del Maule
    TALCA("Talca"),
    CONSTITUCION("Constitución"),
    CUREPTO("Curepto"),
    EMPEDRADO("Empedrado"),
    MAULE("Maule"),
    PELARCO("Pelarco"),
    PENCAHUE("Pencahue"),
    RIO_CLARO("Río Claro"),
    SAN_CLEMENTE("San Clemente"),
    SAN_RAFAEL("San Rafael"),
    CAUQUENES("Cauquenes"),
    CHANCO("Chanco"),
    PELLUHUE("Pelluhue"),
    CURICO("Curicó"),
    HUALAÑE("Hualañé"),
    LICANTEN("Licantén"),
    MOLINA("Molina"),
    RAUCO("Rauco"),
    ROMERAL("Romeral"),
    SAGRADA_FAMILIA("Sagrada Familia"),
    TENO("Teno"),
    VICHUQUEN("Vichuquén"),
    LINARES("Linares"),
    COLBUN("Colbún"),
    LONGAVI("Longaví"),
    PARRAL("Parral"),
    RETIRO("Retiro"),
    SAN_JAVIER("San Javier"),
    VILLA_ALEGRE("Villa Alegre"),
    YERBAS_BUENAS("Yerbas Buenas"),

    // XVI Región de Ñuble
    COBQUECURA("Cobquecura"),
    COELEMU("Coelemu"),
    NINHUE("Ninhue"),
    PORTEZUELO("Portezuelo"),
    QUIRIHUE("Quirihue"),
    RANQUIL("Ránquil"),
    TREGUACO("Treguaco"),
    BULNES("Bulnes"),
    CHILLAN_VIEJO("Chillán Viejo"),
    CHILLAN("Chillán"),
    EL_CARMEN("El Carmen"),
    PEMUCO("Pemuco"),
    PINTO("Pinto"),
    QUILLON("Quillón"),
    SAN_IGNACIO("San Ignacio"),
    YUNGAY("Yungay"),
    COIHUECO("Coihueco"),
    NIQUEÑAN("Ñiquén"),
    SAN_CARLOS("San Carlos"),
    SAN_FABIAN("San Fabián"),
    SAN_NICOLAS("San Nicolás"),

    // VIII Región del Biobío
    CONCEPCION("Concepción"),
    CORONEL("Coronel"),
    CHIGUAYANTE("Chiguayante"),
    FLORIDA("Florida"),
    HUALQUI("Hualqui"),
    LOTA("Lota"),
    PENCO("Penco"),
    SAN_PEDRO_DE_LA_PAZ("San Pedro de la Paz"),
    SANTA_JUANA("Santa Juana"),
    TALCAHUANO("Talcahuano"),
    TOME("Tomé"),
    HUALPEN("Hualpén"),
    LEBU("Lebu"),
    ARAUCO("Arauco"),
    CAÑETE("Cañete"),
    CONTULMO("Contulmo"),
    CURANILAHUE("Curanilahue"),
    LOS_ALAMOS("Los Álamos"),
    TIRUA("Tirúa"),
    LOS_ANGELES("Los Ángeles"),
    ANTUCO("Antuco"),
    CABRERO("Cabrero"),
    LAJA("Laja"),
    MULCHEN("Mulchén"),
    NACIMIENTO("Nacimiento"),
    NEGRETE("Negrete"),
    QUILACO("Quilaco"),
    QUILLECO("Quilleco"),
    SAN_ROSENDO("San Rosendo"),
    SANTA_BARBARA("Santa Bárbara"),
    TUCAPEL("Tucapel"),
    YUMBEL("Yumbel"),
    ALTO_BIOBIO("Alto Biobío"),

    // IX Región de la Araucanía
    TEMUCO("Temuco"),
    CARAHUE("Carahue"),
    CUNCO("Cunco"),
    CURARREHUE("Curarrehue"),
    FREIRE("Freire"),
    GALVARINO("Galvarino"),
    GORBEA("Gorbea"),
    LAUTARO("Lautaro"),
    LONCOCHE("Loncoche"),
    MELIPEUCO("Melipeuco"),
    NUEVA_IMPERIAL("Nueva Imperial"),
    PADRE_LAS_CASAS("Padre las Casas"),
    PERQUENCO("Perquenco"),
    PITRUFQUEN("Pitrufquén"),
    PUCON("Pucón"),
    SAAVEDRA("Saavedra"),
    TEODORO_SCHMIDT("Teodoro Schmidt"),
    TOLTEN("Toltén"),
    VILCUN("Vilcún"),
    VILLARRICA("Villarrica"),
    CHOLCHOL("Cholchol"),
    ANGOL("Angol"),
    COLLIULLI("Collipulli"),
    CURACAUTIN("Curacautín"),
    ERCILLA("Ercilla"),
    LONQUIMAY("Lonquimay"),
    LOS_SAUCES("Los Sauces"),
    LUMACO("Lumaco"),
    PUREN("Purén"),
    RENAICO("Renaico"),
    TRAIGUEN("Traiguén"),
    VICTORIA("Victoria"),

    // XIV Región de Los Ríos
    VALDIVIA("Valdivia"),
    CORRAL("Corral"),
    LANCO("Lanco"),
    LOS_LAGOS("Los Lagos"),
    MAFIL("Máfil"),
    MARIQUINA("Mariquina"),
    PAILLACO("Paillaco"),
    PANGUPIULLI("Panguipulli"),
    LA_UNION("La Unión"),
    FUTRONO("Futrono"),
    LAGO_RANCO("Lago Ranco"),
    RIO_BUENO("Río Bueno"),

    // X Región de Los Lagos
    PUERTO_MONTT("Puerto Montt"),
    CALBUCO("Calbuco"),
    COCHAMO("Cochamó"),
    FRESIA("Fresia"),
    FRUTILLAR("Frutillar"),
    LOS_MUERMOS("Los Muermos"),
    LLANQUIHUE("Llanquihue"),
    MAULLIN("Maullín"),
    PUERTO_VARAS("Puerto Varas"),
    CASTRO("Castro"),
    ANCUD("Ancud"),
    CHONCHI("Chonchi"),
    CURACO_DE_VELEZ("Curaco de Vélez"),
    DALCAHUE("Dalcahue"),
    PUQUELDON("Puqueldón"),
    QUEILEN("Queilén"),
    QUELLON("Quellón"),
    QUEMCHI("Quemchi"),
    QUINCHAO("Quinchao"),
    OSORNO("Osorno"),
    PUERTO_OCTAY("Puerto Octay"),
    PURRANQUE("Purranque"),
    PUYEHUE("Puyehue"),
    RIO_NEGRO("Río Negro"),
    SAN_JUAN_DE_LA_COSTA("San Juan de la Costa"),
    SAN_PABLO("San Pablo"),
    CHAITEN("Chaitén"),
    FUTALEUFU("Futaleufú"),
    HUALAIHUE("Hualaihué"),
    PALENA("Palena"),

    // XI Región de Aysén
    COIHAIQUE("Coyhaique"),
    LAGO_VERDE("Lago Verde"),
    AISEN("Aisén"),
    CISNES("Cisnes"),
    GUAITECAS("Guaitecas"),
    COCHRANE("Cochrane"),
    OHIGGINS("O'Higgins"),
    TORTEL("Tortel"),
    CHILE_CHICO("Chile Chico"),
    RIO_IBANEZ("Río Ibáñez"),

    // XII Región de Magallanes
    PUNTA_ARENAS("Punta Arenas"),
    LAGUNA_BLANCA("Laguna Blanca"),
    RIO_VERDE("Río Verde"),
    SAN_GREGORIO("San Gregorio"),
    CABO_DE_HORNOS("Cabo de Hornos"),
    ANTARTICA("Antártica"),
    PORVENIR("Porvenir"),
    PRIMAVERA("Primavera"),
    TIMAUKEL("Timaukel"),
    NATALES("Natales"),
    TORRES_DEL_PAINE("Torres del Paine"),

    // RM Región Metropolitana de Santiago
    CERRILLOS("Cerrillos"),
    CERRO_NAVIA("Cerro Navia"),
    CONCHALI("Conchalí"),
    EL_BOSQUE("El Bosque"),
    ESTACION_CENTRAL("Estación Central"),
    HUECHURABA("Huechuraba"),
    INDEPENDENCIA("Independencia"),
    LA_CISTERNA("La Cisterna"),
    LA_FLORIDA("La Florida"),
    LA_GRANJA("La Granja"),
    LA_PINTANA("La Pintana"),
    LA_REINA("La Reina"),
    LAS_CONDES("Las Condes"),
    LO_BARNECHEA("Lo Barnechea"),
    LO_ESPEJO("Lo Espejo"),
    LO_PRADO("Lo Prado"),
    MACUL("Macul"),
    MAIPU("Maipú"),
    NUNOA("Ñuñoa"),
    PEDRO_AGUIRRE_CERDA("Pedro Aguirre Cerda"),
    PENALOLEN("Peñalolén"),
    PROVIDENCIA("Providencia"),
    PUDAHUEL("Pudahuel"),
    QUILICURA("Quilicura"),
    QUINTA_NORMAL("Quinta Normal"),
    RECOLETA("Recoleta"),
    RENCA("Renca"),
    SAN_JOAQUIN("San Joaquín"),
    SAN_MIGUEL("San Miguel"),
    SAN_RAMON("San Ramón"),
    VITACURA("Vitacura"),
    PUENTE_ALTO("Puente Alto"),
    PIRQUE("Pirque"),
    SAN_JOSE_DE_MAIPO("San José de Maipo"),
    BUIN("Buin"),
    CALERA_DE_TANGO("Calera de Tango"),
    PAINE("Paine"),
    SAN_BERNARDO("San Bernardo"),
    ALHUE("Alhué"),
    CURACAVI("Curacaví"),
    MARIA_PINTO("María Pinto"),
    MELIPILLA("Melipilla"),
    SAN_PEDRO("San Pedro"),
    TALAGANTE("Talagante"),
    COLINA("Colina"),
    LAMPA("Lampa"),
    TILTIL("Tiltil"),
    SANTIAGO("Santiago");

    private final String displayName;

    Comuna(String displayName) {
        this.displayName = displayName;
    }
}
